# Generated by Django 3.1.4 on 2020-12-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Último Nome')),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('pages', models.IntegerField(verbose_name='Páginas')),
                ('publish_date', models.DateField(verbose_name='Data da publicação')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author', verbose_name='Autor')),
            ],
        ),
    ]
